/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as TodayRouteImport } from './routes/today'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as MerchantsNewRouteImport } from './routes/merchants.new'
import { Route as MerchantsMerchantIdRouteImport } from './routes/merchants.$merchantId'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/watch.lazy').then((d) => d.Route))
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/today.lazy').then((d) => d.Route))
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recommend.lazy').then((d) => d.Route))
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/purchases.lazy').then((d) => d.Route))
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/merchants.lazy').then((d) => d.Route))
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/discovery.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any).lazy(() =>
  import('./routes/products.$productId.lazy').then((d) => d.Route),
)
const MerchantsNewRoute = MerchantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantsRoute,
} as any)
const MerchantsMerchantIdRoute = MerchantsMerchantIdRouteImport.update({
  id: '/$merchantId',
  path: '/$merchantId',
  getParentRoute: () => MerchantsRoute,
} as any).lazy(() =>
  import('./routes/merchants.$merchantId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/merchants': typeof MerchantsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/recommend': typeof RecommendRoute
  '/today': typeof TodayRoute
  '/watch': typeof WatchRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/merchants/new': typeof MerchantsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/merchants': typeof MerchantsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/recommend': typeof RecommendRoute
  '/today': typeof TodayRoute
  '/watch': typeof WatchRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/merchants/new': typeof MerchantsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/merchants': typeof MerchantsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/recommend': typeof RecommendRoute
  '/today': typeof TodayRoute
  '/watch': typeof WatchRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/merchants/new': typeof MerchantsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discovery'
    | '/merchants'
    | '/products'
    | '/purchases'
    | '/recommend'
    | '/today'
    | '/watch'
    | '/merchants/$merchantId'
    | '/merchants/new'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery'
    | '/merchants'
    | '/products'
    | '/purchases'
    | '/recommend'
    | '/today'
    | '/watch'
    | '/merchants/$merchantId'
    | '/merchants/new'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/discovery'
    | '/merchants'
    | '/products'
    | '/purchases'
    | '/recommend'
    | '/today'
    | '/watch'
    | '/merchants/$merchantId'
    | '/merchants/new'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryRoute: typeof DiscoveryRoute
  MerchantsRoute: typeof MerchantsRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  PurchasesRoute: typeof PurchasesRoute
  RecommendRoute: typeof RecommendRoute
  TodayRoute: typeof TodayRoute
  WatchRoute: typeof WatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/merchants/new': {
      id: '/merchants/new'
      path: '/new'
      fullPath: '/merchants/new'
      preLoaderRoute: typeof MerchantsNewRouteImport
      parentRoute: typeof MerchantsRoute
    }
    '/merchants/$merchantId': {
      id: '/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof MerchantsMerchantIdRouteImport
      parentRoute: typeof MerchantsRoute
    }
  }
}

interface MerchantsRouteChildren {
  MerchantsMerchantIdRoute: typeof MerchantsMerchantIdRoute
  MerchantsNewRoute: typeof MerchantsNewRoute
}

const MerchantsRouteChildren: MerchantsRouteChildren = {
  MerchantsMerchantIdRoute: MerchantsMerchantIdRoute,
  MerchantsNewRoute: MerchantsNewRoute,
}

const MerchantsRouteWithChildren = MerchantsRoute._addFileChildren(
  MerchantsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryRoute: DiscoveryRoute,
  MerchantsRoute: MerchantsRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  PurchasesRoute: PurchasesRoute,
  RecommendRoute: RecommendRoute,
  TodayRoute: TodayRoute,
  WatchRoute: WatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
