/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantsNewRouteImport } from './routes/merchants.new'
import { Route as MerchantsMerchantIdRouteImport } from './routes/merchants.$merchantId'

const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsNewRoute = MerchantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantsRoute,
} as any)
const MerchantsMerchantIdRoute = MerchantsMerchantIdRouteImport.update({
  id: '/$merchantId',
  path: '/$merchantId',
  getParentRoute: () => MerchantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/merchants': typeof MerchantsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/recommend': typeof RecommendRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/merchants/new': typeof MerchantsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/merchants': typeof MerchantsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/recommend': typeof RecommendRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/merchants/new': typeof MerchantsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/merchants': typeof MerchantsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/recommend': typeof RecommendRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/merchants/new': typeof MerchantsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discovery'
    | '/merchants'
    | '/purchases'
    | '/recommend'
    | '/merchants/$merchantId'
    | '/merchants/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery'
    | '/merchants'
    | '/purchases'
    | '/recommend'
    | '/merchants/$merchantId'
    | '/merchants/new'
  id:
    | '__root__'
    | '/'
    | '/discovery'
    | '/merchants'
    | '/purchases'
    | '/recommend'
    | '/merchants/$merchantId'
    | '/merchants/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryRoute: typeof DiscoveryRoute
  MerchantsRoute: typeof MerchantsRouteWithChildren
  PurchasesRoute: typeof PurchasesRoute
  RecommendRoute: typeof RecommendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/new': {
      id: '/merchants/new'
      path: '/new'
      fullPath: '/merchants/new'
      preLoaderRoute: typeof MerchantsNewRouteImport
      parentRoute: typeof MerchantsRoute
    }
    '/merchants/$merchantId': {
      id: '/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof MerchantsMerchantIdRouteImport
      parentRoute: typeof MerchantsRoute
    }
  }
}

interface MerchantsRouteChildren {
  MerchantsMerchantIdRoute: typeof MerchantsMerchantIdRoute
  MerchantsNewRoute: typeof MerchantsNewRoute
}

const MerchantsRouteChildren: MerchantsRouteChildren = {
  MerchantsMerchantIdRoute: MerchantsMerchantIdRoute,
  MerchantsNewRoute: MerchantsNewRoute,
}

const MerchantsRouteWithChildren = MerchantsRoute._addFileChildren(
  MerchantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryRoute: DiscoveryRoute,
  MerchantsRoute: MerchantsRouteWithChildren,
  PurchasesRoute: PurchasesRoute,
  RecommendRoute: RecommendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
